##############################################################
### BananaMapRender configuration file - Review carefully! ###
##############################################################

#You MUST set this to a directory or subdirectory path for the map to be stored into.
#Folders for each of your worlds will be created here; Copy the template files into each of them.
directory: 'plugins/BukkitHTTPD/'

#Amount of rendering threads used to generate the tiles. Lower if your server is being overwhelmed.
#Never make it greater than the amount of physical cores in your CPU or CPUs.
max-threads: 2

#Amount of hours it takes for a tile to expire and require an update.
expiration-hours: 1

#How often, in minutes, should expired tiles with players in them be updated.
tile-checker-frequency: 5

#How often should all the markers in the map be updated, also in minutes.
marker-updates-frequency: 1

#Depth shading on tiles (slower).
depth:
    ground: true
    water: true
    lava: true
    
#You can redefine the map palette here by providing R,G,B values (0 to 255) for each block type.
#The default palette colors will be used for each block type you don't define here.
colors:
    i0: [255,255,255]

#Define colors here if you want a block's color to depend on its data byte (useful for wool, etc.)
#This block has priority over 'colors'. Colors are defined in order for each data byte (from 0).
multi-colors:
#    i18:
#        - [34,100,34]
#        - [40,72,0]
#        - [20,105,36]

#WorldBorder integration
worldborder:
    enable: true
    color: '#ff0000'
    opacity: 0.5
    fill-opacity: 0.0

#WorldGuard integration
worldguard-regions:
    enable: true
    color: '#0033ff'
    opacity: 0.5
    fill-opacity: 0.1

#Entity marker options
entities:

    #Blanket enable or disable entities. Disable here for maximum efficiency.
    #Must be enabled for all the other options in this block to work.
    enable: true
    
    #How many mobs to mark in each chunk (don't set this too high or the viewer will be slow).
    max-per-chunk: 3

    #Enable or disable each type of mob separately if you want:
    mobs:
        Pig: true
        Cow: true
        Sheep: true
        Chicken: true
        Creeper: true
        Skeleton: true
        Spider: true
        Zombie: true
        Wolf: true
        PigZombie: true
        Ghast: true
        Slime: true
        Squid: true
    
    #Enable or disable player position markers    
    players: true
    
    #Enable or disable player name popups when the markers are clicked (requires player markers)
    player-popups: true
    
    #Enable or disable tamed wolves. If this is enabled, tamed wolves always show, they have a
    # different icon (red collar) and you can click them to see the name of their owner.
    tamed-wolves: true
    
#Tile entity marker options
tile-entities:

    #Blanket enable or disable tile entities. Disable here for maximum efficiency.
    #Must be enabled for all the other options in this block to work.
    enable: true
    
    #How many tile entities to mark in each chunk (don't set too high or the viewer will be slow).
    max-per-chunk: 3
    
    #Show creature spawners?
    spawners: false
    
    #If creature spawners are enabled, this is the chance of them actually showing.
    spawner-chance: 0.2
    
    #Show BMR signs? BMR signs are signs with [BMR] in the first line. Clicking the icon will
    #display the sign contents.
    signs: true
